### ISSUE TITLE
Can I upgrade current nagios version?

### ISSUE THREAD

**Issue by krish2304** [thias/puppet-nagios#101]
Hello Thias,

           Thank you for providing this module. How can we upgrade the Nagios core server using this module or is it possible to install a specific Nagios core server version

**Comment by blandman** [comment]
Here's what I did,

generated a module to hold all nagios config `puppet generate psd_nagios`

Included the class in my site.pp `include psd_nagios`

In the module create the following files

**psd_nagios/lib/facter/nagios_version.rb**
```
#!/usr/bin/ruby

require 'facter'

Facter.add(:nagios_version) do
  setcode do
   Facter::Core::Execution.exec("nagios --version | sed -n 2p | awk -F 'Core ' '{print $2}'")
  end
end

```

**psd_nagios/templates/install.sh.erb**
```
#!/bin/bash
cd /root/
wget https://assets.nagios.com/downloads/nagioscore/releases/nagios-<%= @desiredVersion %>.tar.gz
tar xzf nagios-<%= @desiredVersion %>.tar.gz
cd nagios-<%= @desiredVersion %>
./configure --with-command-group=nagcmd
make all
make install
/usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg
```
(From [here](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/upgrading.html))

Inside of the main class **psd_nagios/manifests/init.pp**
```
        $installedVersion = $facts["nagios_version"]
	$desiredVersion = "4.2.4"

	if($installedVersion != $desiredVersion){
	  notify {'Version: $installedVersion': }
	  file {'/root/install.sh':
	      ensure => 'file',
	      path => '/root/install.sh',
	      content => template('psd_nagios/install.sh.erb'),
	      owner => 'nagios',
	      group => 'nagios',
	      mode  => '0755',
	      notify => Exec['install_nagios'],
	  }
	  exec { 'install_nagios':
	      command => "/bin/bash -c '/root/install.sh'",
	       notify => Service["nagios"],
	  }
       }
```

Simply update the `$desiredVersion` variable whenever an update is needed.

**Comment by krish2304** [comment]
Thanks a lot
