### ISSUE TITLE
Typo in ntp_time class

### ISSUE THREAD

**Issue by raiblue** [thias/puppet-nagios#50]
Hello,
When no override to nagios::check::ntp_time args, there comes no space between default ntp host and other args, causing an output such as:
command[check_ntp_time]=/usr/lib64/nagios/plugins/check_ntp_time -H 0.pool.ntp.org-w 1 -c 2

So a space is missing in manifests/check/ntp_time.pp line 20. It should be:
  if $args !~ /-H/ { $arg_host = '-H 0.pool.ntp.org ' } else { $arg_host = '' }

**Comment by thias** [comment]
You are absolutely right. This should now be fixed in 5173501964a519bcecc286b918c058a3029cc3c0 and will be included in 1.0.6.
