### ISSUE TITLE
Yum Repo for Extra Packages

### ISSUE THREAD

**Issue by clintonm9** [thias/puppet-nagios#78]
I was trying to add your index of rpm as a repo. 
```

cat /etc/yum.repos.d/nagios.repo 
[nagios]
baseurl=http://dl.marmotte.net/rpms/redhat/el7/x86_64
enabled=1
gpgcheck=1
gpgkey=http://dl.marmotte.net/rpms/RPM-GPG-KEY-matthias

```

Is there a way to let yum handle this without downloading each rpm and installing? 

I get http://dl.marmotte.net/rpms/redhat/el7/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found

**Comment by thias** [comment]
Indeed... the packages I publish there are meant to be "cherry picked" and copied (or even rebuilt) into people's internal repositories. I really don't want that location to become a repository on which some people are relying for production systems, sorry, as I push a lot of stuff there, even some packages that update RHEL base packages. So it's really in everyone's best interest!
