### ISSUE TITLE
How to disable the nginx check in hiera data

### ISSUE THREAD

**Issue by Existentialist1** [thias/puppet-nagios#82]
Hi All,

I am struggling to disable the nginx check via the hieradata.

should this have done the trick?:

`nagios::check::nginx::ensure: absent`

using version 1.0.6

Cheers

**Comment by yevtushenko** [comment]
Version 1.0.6 doesn't support disabling nginx checks using Hiera. This feature was added in 0a545b0 (version 1.0.8).

In v 1.0.6 you can disable check_nginx using the custom fact
```
nagios_check_nginx_disable = true
```

You can add such fact to the you ENC if you use it or directly on the node.

To add nagios_check_nginx_disable fact on the node create file /etc/facter/facts.d/disable_check_nginx.yaml with the following contents:
```
nagios_check_nginx_disable: true
```
